{
    'name': 'iCatch Customization',
    'version':  '13.0.1.0.0',
    'category': 'Productivity',
    'author':   'AB',
    'website':  'www.ab.com',
    'license':  'AGPL-3',
    'summary':  'Misc. Customization',
    'description':  """Misc. Customization""",
    'depends': ['base', 'sale', 'purchase',],
    'data': [
        'security/ir.model.access.csv',
        'data/survey_sale_order_sequence.xml',
        'views/inherit_res_partner.xml',
        'views/inherit_product_form.xml',
        'views/brand.xml',
        'views/campaign.xml',
        'views/customize_sale_order.xml',
        'views/city.xml',
        'views/shop.xml',
        'views/media_description.xml',
        'views/printer.xml',
        'views/ink_type.xml',
        'views/resolution.xml',
        'views/medium_description.xml',
        'views/customize_purchase_order.xml',
        'views/survey_sale_order.xml',
        'views/template.xml',
        'views/customize_invoice.xml',
        'views/extend_stock_move.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable':  True,
    'application':  True,
    'auto_install': False,
}